/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WarehouseRole;

import Business.Organization.Warehouse;
import Business.WorkQueue.Storage;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author xia.jia
 */
public class CreateInventoryJPanel extends javax.swing.JPanel {
    
    private JPanel container;
    private Warehouse organization;
    /**
     * Creates new form CreateInventory
     */

    CreateInventoryJPanel(JPanel container, Warehouse organization) {
        initComponents();
        this.container=container;
        this.organization=organization;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtunitprice = new javax.swing.JTextField();
        BtnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        BtnBack.setText("< Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel1.setText("View Storage");

        jLabel2.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel2.setText("ProductModel:");

        txtmodel.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel3.setText("Quantity:");

        txtquantity.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel4.setText("UnitPrice:");

        txtunitprice.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N

        BtnCreate.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(273, 273, 273))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtunitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BtnCreate)
                .addGap(127, 127, 127)
                .addComponent(BtnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();

        Component[] comps = this.container.getComponents();
        for(Component comp:comps){
            if(comp instanceof SupplierWarehouseJPanel){
                SupplierWarehouseJPanel manageP=(SupplierWarehouseJPanel) comp;
                manageP.popluateInventoryjTable();
            }
        }
        layout.previous(container);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        
        if(txtmodel.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input the ProductModel for the Material");
            return;
        }
        
        try{
            Integer.parseInt(txtquantity.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for quantity");
            return;
        }
        
        try{
            Integer.parseInt(txtunitprice.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a number for unitprice");
            return;
        }
        
        
        Storage storage = new Storage();
        storage.getMaterial().setProductionModel(txtmodel.getText());
        storage.setQuantity(Integer.parseInt(txtquantity.getText()));
        storage.getMaterial().setUnitPrice(Integer.parseInt(txtunitprice.getText()));

        organization.getInventory().add(storage);
        JOptionPane.showMessageDialog(null, "Storage Created Successfully");
    }//GEN-LAST:event_BtnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtunitprice;
    // End of variables declaration//GEN-END:variables
}
