/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinanceRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FinanceDepartment;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class CompanyFinanceWorkPlaceJPanel extends javax.swing.JPanel {
    
    private JPanel container;
    private FinanceDepartment organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    
    /**
     * Creates new form CompanyFinanceWorkPlaceJPanel
     */

    public CompanyFinanceWorkPlaceJPanel(JPanel container, FinanceDepartment organization, Enterprise enterprise, UserAccount userAccount, Network network) {
        initComponents();
        this.container = container;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network=network;
        enterpriseTxt.setText(enterprise.getName());
        populateBilljTable();
    }
    
    public void populateBilljTable(){
        DefaultTableModel model = (DefaultTableModel) billjTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getMaterial().getProductionModel();
            row[2] = request.getQuantity();
            row[3] = request.getMaterial().getUnitPrice();
            row[4] = request.getQuantity()*request.getMaterial().getUnitPrice();
            if(((FinanceTestWorkRequest)request).isDeliveryStatus()){
                row[5] = "Delivered";
            }else{
                row[5] = "Not delivered";
            }    
            if(((FinanceTestWorkRequest)request).isFinanceStatus()){
                row[6] = "Paid";
            }else{
                row[6] = "Unpaid";
            } 
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billjTable = new javax.swing.JTable();
        payBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise: ");

        enterpriseTxt.setEditable(false);

        jLabel2.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel2.setText("Bill Information");

        billjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DeliveryNumber", "ProductModel", "Quantity", "UnitPrice", "TotalPrice", "Delivery Status", "Finance Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(billjTable);
        if (billjTable.getColumnModel().getColumnCount() > 0) {
            billjTable.getColumnModel().getColumn(0).setResizable(false);
            billjTable.getColumnModel().getColumn(1).setResizable(false);
            billjTable.getColumnModel().getColumn(2).setResizable(false);
            billjTable.getColumnModel().getColumn(3).setResizable(false);
            billjTable.getColumnModel().getColumn(4).setResizable(false);
            billjTable.getColumnModel().getColumn(5).setResizable(false);
            billjTable.getColumnModel().getColumn(6).setResizable(false);
        }

        payBtn.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        payBtn.setText("Pay the Bill");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(payBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(payBtn)
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = billjTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table to pay the bill","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            FinanceTestWorkRequest request=(FinanceTestWorkRequest) billjTable.getValueAt(selectedRow, 0);
            if (!request.isDeliveryStatus()){
                JOptionPane.showMessageDialog(null, "Haven't received the goods, can't pay");
                return;
            }
            request.setFinanceStatus(true);
                  
        }
        populateBilljTable();
    
    }//GEN-LAST:event_payBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billjTable;
    private javax.swing.JTextField enterpriseTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payBtn;
    // End of variables declaration//GEN-END:variables
}
