/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FinanceRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.FinanceDepartment;
import Business.Organization.Organization;
import Business.Organization.SalesDepartment;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceTestWorkRequest;
import Business.WorkQueue.PurchasingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class SupplierFinanceWorkPlaceJPanel extends javax.swing.JPanel {

    private JPanel container;
    private FinanceDepartment organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    /**
     * Creates new form FinanceWorkPlaceJPanel
     */

    public SupplierFinanceWorkPlaceJPanel(JPanel container, FinanceDepartment organization, Enterprise enterprise, UserAccount userAccount,Network network) {
        initComponents();
        this.container = container;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network=network;
        enterpriseTxt.setText(enterprise.getName());
        updateData();
        populateDeliveryNotejTable();
    }
    
    public void updateData(){
        Organization org = null;
        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (o instanceof SalesDepartment){
                org = o;
                break;
            }
        }
        
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            for (WorkRequest req : org.getWorkQueue().getWorkRequestList()){
                if (request.getDeliveryNumber() == req.getDeliveryNumber() && ((PurchasingWorkRequest)req).getOrderStatus().equals("Delivered"))
                    ((FinanceTestWorkRequest)request).setDeliveryStatus(true);
            }
        }
    }
    
    public void populateDeliveryNotejTable(){
        DefaultTableModel model = (DefaultTableModel) deliveryNotejTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getMaterial().getProductionModel();
            row[2] = request.getQuantity();
            row[3] = request.getMaterial().getUnitPrice();
            row[4] = request.getQuantity()*request.getMaterial().getUnitPrice();
            if(((FinanceTestWorkRequest)request).isDeliveryStatus()){
                row[5] = "Delivered";
            }else{
                row[5] = "Not delivered";
            }    
            if(((FinanceTestWorkRequest)request).isFinanceStatus()){
                row[6] = "Paid";
            }else{
                row[6] = "Unpaid";
            }  
            //System.out.println(request.getCompanyName());
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryNotejTable = new javax.swing.JTable();
        generateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel1.setText("Enterprise: ");

        enterpriseTxt.setEditable(false);

        jLabel3.setFont(new java.awt.Font("黑体", 1, 24)); // NOI18N
        jLabel3.setText("Delivery Note");

        deliveryNotejTable.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        deliveryNotejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DeliveryNumber", "ProductModel", "Quantity", "UnitPrice", "TotalPrice", "DeliveryStatus", "FinanceStatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deliveryNotejTable);
        if (deliveryNotejTable.getColumnModel().getColumnCount() > 0) {
            deliveryNotejTable.getColumnModel().getColumn(0).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(1).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(2).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(3).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(4).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(5).setResizable(false);
            deliveryNotejTable.getColumnModel().getColumn(6).setResizable(false);
        }

        generateBtn.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        generateBtn.setText("Generate Bill");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(391, 391, 391)
                                .addComponent(generateBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(generateBtn)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = deliveryNotejTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            FinanceTestWorkRequest bill=(FinanceTestWorkRequest) deliveryNotejTable.getValueAt(selectedRow, 0);
            BillJPanel panel = new BillJPanel(container,bill,organization,enterprise,network,userAccount);
            container.add("BillJPanel",panel);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }
    }//GEN-LAST:event_generateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable deliveryNotejTable;
    private javax.swing.JTextField enterpriseTxt;
    private javax.swing.JButton generateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
