/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mac
 */
public class AdminWorkPlaceJPanel extends javax.swing.JPanel {

    private JPanel container;
    private Enterprise enterprise;
    private EcoSystem system;
    
    /**
     * Creates new form AdminWorkPlace
     */

    public AdminWorkPlaceJPanel(JPanel container, Enterprise enterprise,EcoSystem system) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.system = system;
        enterpriseTxt.setText(enterprise.getName());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseTxt = new javax.swing.JTextField();
        BtnManageOrg = new javax.swing.JButton();
        BtnManageEmp = new javax.swing.JButton();
        BtnManageUser = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel1.setText("Work Place");

        jLabel2.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        jLabel2.setText("Enterprise: ");

        enterpriseTxt.setEditable(false);
        enterpriseTxt.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N

        BtnManageOrg.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        BtnManageOrg.setText("Manage Organization");
        BtnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageOrgActionPerformed(evt);
            }
        });

        BtnManageEmp.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        BtnManageEmp.setText("Manage Employee");
        BtnManageEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageEmpActionPerformed(evt);
            }
        });

        BtnManageUser.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        BtnManageUser.setText("Manage User");
        BtnManageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnManageUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnManageEmp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnManageOrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(366, 366, 366))))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(enterpriseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(BtnManageOrg)
                .addGap(56, 56, 56)
                .addComponent(BtnManageEmp)
                .addGap(51, 51, 51)
                .addComponent(BtnManageUser)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageOrgActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel panel= new  ManageOrganizationJPanel(container,enterprise.getOrganizationDirectory(),enterprise);
        container.add(" ManageOrganizationJPanel",panel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_BtnManageOrgActionPerformed

    private void BtnManageEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageEmpActionPerformed
        // TODO add your handling code here:
        ManageEmployeeJPanel panel= new ManageEmployeeJPanel(container,enterprise.getOrganizationDirectory());
        container.add("ManageEmployeeJPanel",panel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_BtnManageEmpActionPerformed

    private void BtnManageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageUserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel panel= new ManageUserAccountJPanel(container,enterprise,system);
        container.add("ManageUserAccountJPanel",panel);
        
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_BtnManageUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageEmp;
    private javax.swing.JButton BtnManageOrg;
    private javax.swing.JButton BtnManageUser;
    private javax.swing.JTextField enterpriseTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
